export * from './Breeds/Breeds.page';
export * from './BreedItem/BreedItem.page';
export * from './Images/Images.page';
export * from './Favorites/Favorites.page';
export * from './Error/Error.page';
export * from './Votes/Votes.page';
export * from './YourUploads/YourUploads.page';
export * from './history/History.page';
export * from './Uploads/Uploads.page';
